AWSTemplateFormatVersion: "2010-09-09"
Description: "Criação de um bucket S3 para o desafio DIO"

Resources:
  MeuBucketS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: kamily-cloudformation-lab
      VersioningConfiguration:
        Status: Enabled

Outputs:
  BucketName:
    Description: Nome do bucket criado
    Value: !Ref MeuBucketS3
